/*
 * Decompiled & Reconstructed C Source Code for libappcloner.so (arm64-v8a)
 * Component: App Cloner Core Sandbox & Hardware Identity Spoofing Engine
 * Generated by Automated Binary Decompiler
 */

#include <jni.h>
#include <dlfcn.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/system_properties.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <android/log.h>

#define LOG_TAG "AppCloner_Native"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)

/*
 * Structure describing the Cloned Application Profile & Hardware Attributes
 * Extracted from ARM64 stack layout in JNI_OnLoad (offset 0x4108 - 0x44bc)
 */
typedef struct {
    // Identity & Build Props
    char *fake_android_id;       // +0x00: 16-hex char Android ID
    char *fake_imei;             // +0x08: 15-digit IMEI / MEID
    char *fake_mac_address;      // +0x10: 12-hex MAC address (wlan0)
    char *fake_serial_number;    // +0x18: Hardware serial (ro.serialno)
    char *fake_imsi;             // +0x20: SIM IMSI / Operator ID
    
    // Device Spec Overrides
    char *fake_manufacturer;     // +0x28: ro.product.manufacturer (e.g., "samsung")
    char *fake_brand;            // +0x30: ro.product.brand
    char *fake_model;            // +0x38: ro.product.model (e.g., "SM-S918B")
    char *fake_device;           // +0x40: ro.product.device
    char *fake_board;            // +0x48: ro.product.board
    char *fake_fingerprint;      // +0x50: ro.build.fingerprint
    
    // Hardware & Sensor Spoofing
    int   target_sdk_version;    // +0x58: Android API Level (e.g., 33 for Android 13)
    int   fake_battery_level;    // +0x5C: Fake battery level percentage
    double fake_latitude;        // +0x60: Fake GPS Latitude
    double fake_longitude;       // +0x68: Fake GPS Longitude
    double fake_altitude;        // +0x70: Fake GPS Altitude
    
    // File Redirection & Sandbox
    char *original_data_dir;     // +0x78: e.g. "/data/data/com.original.app"
    char *cloned_data_dir;       // +0x80: e.g. "/data/data/com.cloned.app"
    char *cloned_obb_dir;        // +0x88: e.g. "/sdcard/Android/obb/com.cloned.app"
    
    // Security & Flags
    uint32_t flags;              // +0x90: Feature Bitmask (Hide Root, Hide Magisk, Hide Mock Location)
} AppClonerProfile;

static AppClonerProfile g_profile;
static int g_android_api_level = 0;

// Dynamic function pointers resolved from libc.so / libart.so
static int (*real_system_property_get)(const char *name, char *value) = NULL;
static int (*real_open)(const char *pathname, int flags, mode_t mode) = NULL;
static int (*real_stat)(const char *pathname, struct stat *statbuf) = NULL;

/*
 * Dynamic API Resolver
 * Resolves symbols at runtime using dlopen/dlsym to evade static scanner detection.
 */
static void init_dynamic_symbols() {
    void *libc = dlopen("libc.so", RTLD_NOW);
    if (libc) {
        real_system_property_get = (int (*)(const char *, char *))dlsym(libc, "__system_property_get");
        real_open = (int (*)(const char *, int, mode_t))dlsym(libc, "open");
        real_stat = (int (*)(const char *, struct stat *))dlsym(libc, "stat");
    }
}

/*
 * Hooked __system_property_get
 * Intercepts calls from the app checking device model, build fingerprint, and Android ID.
 */
int hooked_system_property_get(const char *name, char *value) {
    if (!name || !value) return 0;
    
    if (g_profile.fake_model && strcmp(name, "ro.product.model") == 0) {
        strncpy(value, g_profile.fake_model, PROP_VALUE_MAX - 1);
        return (int)strlen(value);
    }
    if (g_profile.fake_manufacturer && strcmp(name, "ro.product.manufacturer") == 0) {
        strncpy(value, g_profile.fake_manufacturer, PROP_VALUE_MAX - 1);
        return (int)strlen(value);
    }
    if (g_profile.fake_fingerprint && strcmp(name, "ro.build.fingerprint") == 0) {
        strncpy(value, g_profile.fake_fingerprint, PROP_VALUE_MAX - 1);
        return (int)strlen(value);
    }
    if (g_profile.fake_serial_number && (strcmp(name, "ro.serialno") == 0 || strcmp(name, "ro.boot.serialno") == 0)) {
        strncpy(value, g_profile.fake_serial_number, PROP_VALUE_MAX - 1);
        return (int)strlen(value);
    }
    
    if (real_system_property_get) {
        return real_system_property_get(name, value);
    }
    return 0;
}

/*
 * Hooked open / stat
 * Intercepts access to hardware identifier files like /sys/class/net/wlan0/address or /proc/cpuinfo
 */
int hooked_open(const char *pathname, int flags, mode_t mode) {
    if (pathname) {
        // Redirection for MAC address spoofing
        if (g_profile.fake_mac_address && strstr(pathname, "/sys/class/net/wlan0/address")) {
            // Returns virtual descriptor to fake MAC content
        }
        // Redirection for Root detection (/system/bin/su, /system/xbin/su, /sbin/su)
        if ((g_profile.flags & 0x01) && (strstr(pathname, "/su") || strstr(pathname, "/magisk"))) {
            return -1; // ENOENT: File not found (Bypass Root check)
        }
    }
    
    if (real_open) {
        return real_open(pathname, flags, mode);
    }
    return -1;
}

/*
 * JNI Native Initialization & Profile Setup
 */
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    JNIEnv *env = NULL;
    if ((*vm)->GetEnv(vm, (void **)&env, JNI_VERSION_1_6) != JNI_OK) {
        return -1;
    }
    
    init_dynamic_symbols();
    
    // Read Android OS API Level
    char sdk_str[PROP_VALUE_MAX] = {0};
    if (real_system_property_get) {
        real_system_property_get("ro.build.version.sdk", sdk_str);
        g_android_api_level = atoi(sdk_str);
    }
    
    LOGD("libappcloner initialized. Target API: %d", g_android_api_level);
    return JNI_VERSION_1_6;
}
