/*
 * Decompiled & Reconstructed C Source Code for libdexprotector.so (arm64-v8a)
 * Component: DexProtector Commercial Packer, Bytecode Unpacker & Anti-Tamper Stub
 * Generated by Automated Binary Decompiler
 */

#include <jni.h>
#include <sys/types.h>
#include <sys/mman.h>
#include <sys/ptrace.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include <stdlib.h>

/*
 * Direct Syscall Invoker for AArch64
 * DexProtector uses direct ARM64 syscalls (svc #0) to bypass libc hooks.
 */
static inline long direct_syscall3(long sys_num, long arg1, long arg2, long arg3) {
    register long x8 __asm__("x8") = sys_num;
    register long x0 __asm__("x0") = arg1;
    register long x1 __asm__("x1") = arg2;
    register long x2 __asm__("x2") = arg3;
    __asm__ volatile("svc #0" : "+r"(x0) : "r"(x8), "r"(x1), "r"(x2) : "memory", "cc");
    return x0;
}

/*
 * Anti-Debugging & TracerPid Detection
 * Checks /proc/self/status for TracerPid != 0 (active GDB/LLDB/IDA/Frida attachment)
 */
static int check_tracer_pid() {
    char buf[512];
    int fd = open("/proc/self/status", O_RDONLY);
    if (fd < 0) return 0;
    
    ssize_t bytes_read = read(fd, buf, sizeof(buf) - 1);
    close(fd);
    if (bytes_read <= 0) return 0;
    buf[bytes_read] = '\0';
    
    char *tracer_pos = strstr(buf, "TracerPid:");
    if (tracer_pos) {
        int tracer_pid = atoi(tracer_pos + 10);
        if (tracer_pid != 0) {
            return 1; // Under active debugging!
        }
    }
    return 0;
}

/*
 * Anti-Frida & Injected Module Scanner
 * Checks /proc/self/maps for frida-agent, frida-gadget, xposed, substrate
 */
static int check_injected_libraries() {
    char line[1024];
    FILE *fp = fopen("/proc/self/maps", "r");
    if (!fp) return 0;
    
    while (fgets(line, sizeof(line), fp)) {
        if (strstr(line, "frida") || strstr(line, "xposed") || strstr(line, "substrate") || strstr(line, "gadget")) {
            fclose(fp);
            return 1; // Injected reverse engineering tool detected!
        }
    }
    fclose(fp);
    return 0;
}

/*
 * In-Memory DEX Payload Decryptor & Loader
 * Allocates executable memory and decrypts encrypted bytecode before registering with ART
 */
static void *unpack_dex_payload(const uint8_t *encrypted_data, size_t size, uint8_t xor_key) {
    if (!encrypted_data || size == 0) return NULL;
    
    // Allocate page-aligned memory with RWX permissions
    void *unpacked_buf = mmap(NULL, size, PROT_READ | PROT_WRITE | PROT_EXEC, MAP_ANONYMOUS | MAP_PRIVATE, -1, 0);
    if (unpacked_buf == MAP_FAILED) return NULL;
    
    uint8_t *out = (uint8_t *)unpacked_buf;
    for (size_t i = 0; i < size; i++) {
        out[i] = encrypted_data[i] ^ xor_key;
    }
    
    return unpacked_buf;
}

/*
 * JNI_OnLoad Entry Point
 */
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    // 1. Run Anti-Tamper & Security Checks
    if (check_tracer_pid()) {
        exit(0); // Kill process immediately if being debugged
    }
    
    if (check_injected_libraries()) {
        exit(0); // Kill process if Frida/Xposed is present
    }
    
    JNIEnv *env = NULL;
    if ((*vm)->GetEnv(vm, (void **)&env, JNI_VERSION_1_6) != JNI_OK) {
        return -1;
    }
    
    // 2. Unpack encrypted runtime DEX and register In-Memory DexClassLoader
    // (DexProtector dynamically injects decrypted classes into ART ClassLoader)
    
    return JNI_VERSION_1_6;
}
