/*
 * Decompiled & Reconstructed C Source Code for libsystem.so (arm64-v8a)
 * Component: App Cloner Network & IPC Subsystem (net.typeblog.socks.system)
 * Generated by Automated Binary Decompiler
 */

#include <jni.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <android/log.h>

#define LOG_TAG "AppCloner_System"
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)

#define ANCIL_MAX_FDS 8

/*
 * ancil_send_fd
 * Sends a single file descriptor over a UNIX domain socket using SCM_RIGHTS ancillary data.
 */
int ancil_send_fd(int sock, int fd) {
    struct msghdr msg;
    struct iovec iov[1];
    char dummy = '!'; // 0x21
    
    union {
        struct cmsghdr cm;
        char control[CMSG_SPACE(sizeof(int))];
    } control_un;
    
    iov[0].iov_base = &dummy;
    iov[0].iov_len = 1;
    
    memset(&msg, 0, sizeof(msg));
    msg.msg_iov = iov;
    msg.msg_iovlen = 1;
    msg.msg_control = control_un.control;
    msg.msg_controllen = sizeof(control_un.control);
    
    struct cmsghdr *cmsg = CMSG_FIRSTHDR(&msg);
    cmsg->cmsg_len = CMSG_LEN(sizeof(int));
    cmsg->cmsg_level = SOL_SOCKET;
    cmsg->cmsg_type = SCM_RIGHTS;
    *((int *) CMSG_DATA(cmsg)) = fd;
    
    ssize_t res = sendmsg(sock, &msg, 0);
    return (res >= 0) ? 0 : -1;
}

/*
 * ancil_send_fds
 * Sends multiple file descriptors over a UNIX domain socket.
 */
int ancil_send_fds(int sock, const int *fds, unsigned int num_fds) {
    if (num_fds == 0 || num_fds > ANCIL_MAX_FDS) {
        return -1;
    }
    
    struct msghdr msg;
    struct iovec iov[1];
    char dummy = '!';
    
    size_t cmsg_space = CMSG_SPACE(num_fds * sizeof(int));
    char *control_buf = (char *)malloc(cmsg_space);
    if (!control_buf) return -1;
    
    iov[0].iov_base = &dummy;
    iov[0].iov_len = 1;
    
    memset(&msg, 0, sizeof(msg));
    msg.msg_iov = iov;
    msg.msg_iovlen = 1;
    msg.msg_control = control_buf;
    msg.msg_controllen = cmsg_space;
    
    struct cmsghdr *cmsg = CMSG_FIRSTHDR(&msg);
    cmsg->cmsg_len = CMSG_LEN(num_fds * sizeof(int));
    cmsg->cmsg_level = SOL_SOCKET;
    cmsg->cmsg_type = SCM_RIGHTS;
    
    memcpy(CMSG_DATA(cmsg), fds, num_fds * sizeof(int));
    
    ssize_t res = sendmsg(sock, &msg, 0);
    free(control_buf);
    return (res >= 0) ? 0 : -1;
}

/*
 * ancil_send_fds_with_buffer
 */
int ancil_send_fds_with_buffer(int sock, const int *fds, unsigned int num_fds, void *buffer, size_t buffer_len) {
    if (num_fds > ANCIL_MAX_FDS) return -1;
    
    struct msghdr msg;
    struct iovec iov[1];
    char dummy = '!';
    
    iov[0].iov_base = &dummy;
    iov[0].iov_len = 1;
    
    memset(&msg, 0, sizeof(msg));
    msg.msg_iov = iov;
    msg.msg_iovlen = 1;
    msg.msg_control = buffer;
    msg.msg_controllen = buffer_len;
    
    struct cmsghdr *cmsg = (struct cmsghdr *)buffer;
    cmsg->cmsg_len = CMSG_LEN(num_fds * sizeof(int));
    cmsg->cmsg_level = SOL_SOCKET;
    cmsg->cmsg_type = SCM_RIGHTS;
    
    if (fds && num_fds > 0) {
        memcpy(CMSG_DATA(cmsg), fds, num_fds * sizeof(int));
    }
    
    ssize_t res = sendmsg(sock, &msg, 0);
    return (res >= 0) ? 0 : -1;
}

/*
 * Java_net_typeblog_socks_system_jniclose
 * JNI wrapper to close a native socket or file descriptor.
 */
JNIEXPORT void JNICALL Java_net_typeblog_socks_system_jniclose(JNIEnv *env, jobject thiz, jint fd) {
    close(fd);
}

/*
 * Java_net_typeblog_socks_system_sendfd
 * JNI wrapper to connect to a local UNIX domain socket and transfer a file descriptor.
 */
JNIEXPORT jint JNICALL Java_net_typeblog_socks_system_sendfd(JNIEnv *env, jobject thiz, jint fd, jstring sock_path) {
    if (fd < 0 || !sock_path) {
        return -1;
    }
    
    int sock = socket(AF_UNIX, SOCK_STREAM, 0);
    if (sock < 0) {
        return -1;
    }
    
    struct sockaddr_un addr;
    memset(&addr, 0, sizeof(addr));
    addr.sun_family = AF_UNIX;
    
    const char *path = (*env)->GetStringUTFChars(env, sock_path, NULL);
    if (!path) {
        close(sock);
        return -1;
    }
    
    strncpy(addr.sun_path, path, sizeof(addr.sun_path) - 1);
    (*env)->ReleaseStringUTFChars(env, sock_path, path);
    
    if (connect(sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        close(sock);
        return -1;
    }
    
    int ret = ancil_send_fd(sock, fd);
    close(sock);
    return ret;
}

/*
 * JNI_OnLoad
 * Registers native methods dynamically with the ART/Dalvik virtual machine.
 */
static const JNINativeMethod gMethods[] = {
    {"jniclose", "(I)V", (void *)Java_net_typeblog_socks_system_jniclose},
    {"sendfd",   "(ILjava/lang/String;)I", (void *)Java_net_typeblog_socks_system_sendfd}
};

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    JNIEnv *env = NULL;
    if ((*vm)->GetEnv(vm, (void **)&env, JNI_VERSION_1_4) != JNI_OK) {
        LOGE("ERROR: GetEnv failed in libsystem.so JNI_OnLoad");
        return -1;
    }
    
    jclass clazz = (*env)->FindClass(env, "net/typeblog/socks/System");
    if (!clazz) {
        LOGE("Can't find class: net/typeblog/socks/System");
        return -1;
    }
    
    if ((*env)->RegisterNatives(env, clazz, gMethods, sizeof(gMethods) / sizeof(gMethods[0])) < 0) {
        LOGE("ERROR: registerNatives failed for net/typeblog/socks/System");
        return -1;
    }
    
    return JNI_VERSION_1_4;
}
