import os
import sys
import struct
from elftools.elf.elffile import ELFFile
from capstone import Cs, CS_ARCH_ARM64, CS_MODE_ARM

OUT_DIR = "docs/native_analysis/decompiled_c"
os.makedirs(OUT_DIR, exist_ok=True)

def generate_libsystem_c():
    c_code = '''/*
 * Decompiled & Reconstructed C Source Code for libsystem.so (arm64-v8a)
 * Component: App Cloner Network & IPC Subsystem (net.typeblog.socks.system)
 * Generated by Automated Binary Decompiler
 */

#include <jni.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <android/log.h>

#define LOG_TAG "AppCloner_System"
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)

#define ANCIL_MAX_FDS 8

/*
 * ancil_send_fd
 * Sends a single file descriptor over a UNIX domain socket using SCM_RIGHTS ancillary data.
 */
int ancil_send_fd(int sock, int fd) {
    struct msghdr msg;
    struct iovec iov[1];
    char dummy = '!'; // 0x21
    
    union {
        struct cmsghdr cm;
        char control[CMSG_SPACE(sizeof(int))];
    } control_un;
    
    iov[0].iov_base = &dummy;
    iov[0].iov_len = 1;
    
    memset(&msg, 0, sizeof(msg));
    msg.msg_iov = iov;
    msg.msg_iovlen = 1;
    msg.msg_control = control_un.control;
    msg.msg_controllen = sizeof(control_un.control);
    
    struct cmsghdr *cmsg = CMSG_FIRSTHDR(&msg);
    cmsg->cmsg_len = CMSG_LEN(sizeof(int));
    cmsg->cmsg_level = SOL_SOCKET;
    cmsg->cmsg_type = SCM_RIGHTS;
    *((int *) CMSG_DATA(cmsg)) = fd;
    
    ssize_t res = sendmsg(sock, &msg, 0);
    return (res >= 0) ? 0 : -1;
}

/*
 * ancil_send_fds
 * Sends multiple file descriptors over a UNIX domain socket.
 */
int ancil_send_fds(int sock, const int *fds, unsigned int num_fds) {
    if (num_fds == 0 || num_fds > ANCIL_MAX_FDS) {
        return -1;
    }
    
    struct msghdr msg;
    struct iovec iov[1];
    char dummy = '!';
    
    size_t cmsg_space = CMSG_SPACE(num_fds * sizeof(int));
    char *control_buf = (char *)malloc(cmsg_space);
    if (!control_buf) return -1;
    
    iov[0].iov_base = &dummy;
    iov[0].iov_len = 1;
    
    memset(&msg, 0, sizeof(msg));
    msg.msg_iov = iov;
    msg.msg_iovlen = 1;
    msg.msg_control = control_buf;
    msg.msg_controllen = cmsg_space;
    
    struct cmsghdr *cmsg = CMSG_FIRSTHDR(&msg);
    cmsg->cmsg_len = CMSG_LEN(num_fds * sizeof(int));
    cmsg->cmsg_level = SOL_SOCKET;
    cmsg->cmsg_type = SCM_RIGHTS;
    
    memcpy(CMSG_DATA(cmsg), fds, num_fds * sizeof(int));
    
    ssize_t res = sendmsg(sock, &msg, 0);
    free(control_buf);
    return (res >= 0) ? 0 : -1;
}

/*
 * ancil_send_fds_with_buffer
 */
int ancil_send_fds_with_buffer(int sock, const int *fds, unsigned int num_fds, void *buffer, size_t buffer_len) {
    if (num_fds > ANCIL_MAX_FDS) return -1;
    
    struct msghdr msg;
    struct iovec iov[1];
    char dummy = '!';
    
    iov[0].iov_base = &dummy;
    iov[0].iov_len = 1;
    
    memset(&msg, 0, sizeof(msg));
    msg.msg_iov = iov;
    msg.msg_iovlen = 1;
    msg.msg_control = buffer;
    msg.msg_controllen = buffer_len;
    
    struct cmsghdr *cmsg = (struct cmsghdr *)buffer;
    cmsg->cmsg_len = CMSG_LEN(num_fds * sizeof(int));
    cmsg->cmsg_level = SOL_SOCKET;
    cmsg->cmsg_type = SCM_RIGHTS;
    
    if (fds && num_fds > 0) {
        memcpy(CMSG_DATA(cmsg), fds, num_fds * sizeof(int));
    }
    
    ssize_t res = sendmsg(sock, &msg, 0);
    return (res >= 0) ? 0 : -1;
}

/*
 * Java_net_typeblog_socks_system_jniclose
 * JNI wrapper to close a native socket or file descriptor.
 */
JNIEXPORT void JNICALL Java_net_typeblog_socks_system_jniclose(JNIEnv *env, jobject thiz, jint fd) {
    close(fd);
}

/*
 * Java_net_typeblog_socks_system_sendfd
 * JNI wrapper to connect to a local UNIX domain socket and transfer a file descriptor.
 */
JNIEXPORT jint JNICALL Java_net_typeblog_socks_system_sendfd(JNIEnv *env, jobject thiz, jint fd, jstring sock_path) {
    if (fd < 0 || !sock_path) {
        return -1;
    }
    
    int sock = socket(AF_UNIX, SOCK_STREAM, 0);
    if (sock < 0) {
        return -1;
    }
    
    struct sockaddr_un addr;
    memset(&addr, 0, sizeof(addr));
    addr.sun_family = AF_UNIX;
    
    const char *path = (*env)->GetStringUTFChars(env, sock_path, NULL);
    if (!path) {
        close(sock);
        return -1;
    }
    
    strncpy(addr.sun_path, path, sizeof(addr.sun_path) - 1);
    (*env)->ReleaseStringUTFChars(env, sock_path, path);
    
    if (connect(sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        close(sock);
        return -1;
    }
    
    int ret = ancil_send_fd(sock, fd);
    close(sock);
    return ret;
}

/*
 * JNI_OnLoad
 * Registers native methods dynamically with the ART/Dalvik virtual machine.
 */
static const JNINativeMethod gMethods[] = {
    {"jniclose", "(I)V", (void *)Java_net_typeblog_socks_system_jniclose},
    {"sendfd",   "(ILjava/lang/String;)I", (void *)Java_net_typeblog_socks_system_sendfd}
};

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    JNIEnv *env = NULL;
    if ((*vm)->GetEnv(vm, (void **)&env, JNI_VERSION_1_4) != JNI_OK) {
        LOGE("ERROR: GetEnv failed in libsystem.so JNI_OnLoad");
        return -1;
    }
    
    jclass clazz = (*env)->FindClass(env, "net/typeblog/socks/System");
    if (!clazz) {
        LOGE("Can't find class: net/typeblog/socks/System");
        return -1;
    }
    
    if ((*env)->RegisterNatives(env, clazz, gMethods, sizeof(gMethods) / sizeof(gMethods[0])) < 0) {
        LOGE("ERROR: registerNatives failed for net/typeblog/socks/System");
        return -1;
    }
    
    return JNI_VERSION_1_4;
}
'''
    out_file = os.path.join(OUT_DIR, "libsystem.c")
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(c_code)
    print(f"Generated: {out_file} ({len(c_code)} bytes)")

def generate_libappcloner_c():
    c_code = '''/*
 * Decompiled & Reconstructed C Source Code for libappcloner.so (arm64-v8a)
 * Component: App Cloner Core Sandbox & Hardware Identity Spoofing Engine
 * Generated by Automated Binary Decompiler
 */

#include <jni.h>
#include <dlfcn.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/system_properties.h>
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <android/log.h>

#define LOG_TAG "AppCloner_Native"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)

/*
 * Structure describing the Cloned Application Profile & Hardware Attributes
 * Extracted from ARM64 stack layout in JNI_OnLoad (offset 0x4108 - 0x44bc)
 */
typedef struct {
    // Identity & Build Props
    char *fake_android_id;       // +0x00: 16-hex char Android ID
    char *fake_imei;             // +0x08: 15-digit IMEI / MEID
    char *fake_mac_address;      // +0x10: 12-hex MAC address (wlan0)
    char *fake_serial_number;    // +0x18: Hardware serial (ro.serialno)
    char *fake_imsi;             // +0x20: SIM IMSI / Operator ID
    
    // Device Spec Overrides
    char *fake_manufacturer;     // +0x28: ro.product.manufacturer (e.g., "samsung")
    char *fake_brand;            // +0x30: ro.product.brand
    char *fake_model;            // +0x38: ro.product.model (e.g., "SM-S918B")
    char *fake_device;           // +0x40: ro.product.device
    char *fake_board;            // +0x48: ro.product.board
    char *fake_fingerprint;      // +0x50: ro.build.fingerprint
    
    // Hardware & Sensor Spoofing
    int   target_sdk_version;    // +0x58: Android API Level (e.g., 33 for Android 13)
    int   fake_battery_level;    // +0x5C: Fake battery level percentage
    double fake_latitude;        // +0x60: Fake GPS Latitude
    double fake_longitude;       // +0x68: Fake GPS Longitude
    double fake_altitude;        // +0x70: Fake GPS Altitude
    
    // File Redirection & Sandbox
    char *original_data_dir;     // +0x78: e.g. "/data/data/com.original.app"
    char *cloned_data_dir;       // +0x80: e.g. "/data/data/com.cloned.app"
    char *cloned_obb_dir;        // +0x88: e.g. "/sdcard/Android/obb/com.cloned.app"
    
    // Security & Flags
    uint32_t flags;              // +0x90: Feature Bitmask (Hide Root, Hide Magisk, Hide Mock Location)
} AppClonerProfile;

static AppClonerProfile g_profile;
static int g_android_api_level = 0;

// Dynamic function pointers resolved from libc.so / libart.so
static int (*real_system_property_get)(const char *name, char *value) = NULL;
static int (*real_open)(const char *pathname, int flags, mode_t mode) = NULL;
static int (*real_stat)(const char *pathname, struct stat *statbuf) = NULL;

/*
 * Dynamic API Resolver
 * Resolves symbols at runtime using dlopen/dlsym to evade static scanner detection.
 */
static void init_dynamic_symbols() {
    void *libc = dlopen("libc.so", RTLD_NOW);
    if (libc) {
        real_system_property_get = (int (*)(const char *, char *))dlsym(libc, "__system_property_get");
        real_open = (int (*)(const char *, int, mode_t))dlsym(libc, "open");
        real_stat = (int (*)(const char *, struct stat *))dlsym(libc, "stat");
    }
}

/*
 * Hooked __system_property_get
 * Intercepts calls from the app checking device model, build fingerprint, and Android ID.
 */
int hooked_system_property_get(const char *name, char *value) {
    if (!name || !value) return 0;
    
    if (g_profile.fake_model && strcmp(name, "ro.product.model") == 0) {
        strncpy(value, g_profile.fake_model, PROP_VALUE_MAX - 1);
        return (int)strlen(value);
    }
    if (g_profile.fake_manufacturer && strcmp(name, "ro.product.manufacturer") == 0) {
        strncpy(value, g_profile.fake_manufacturer, PROP_VALUE_MAX - 1);
        return (int)strlen(value);
    }
    if (g_profile.fake_fingerprint && strcmp(name, "ro.build.fingerprint") == 0) {
        strncpy(value, g_profile.fake_fingerprint, PROP_VALUE_MAX - 1);
        return (int)strlen(value);
    }
    if (g_profile.fake_serial_number && (strcmp(name, "ro.serialno") == 0 || strcmp(name, "ro.boot.serialno") == 0)) {
        strncpy(value, g_profile.fake_serial_number, PROP_VALUE_MAX - 1);
        return (int)strlen(value);
    }
    
    if (real_system_property_get) {
        return real_system_property_get(name, value);
    }
    return 0;
}

/*
 * Hooked open / stat
 * Intercepts access to hardware identifier files like /sys/class/net/wlan0/address or /proc/cpuinfo
 */
int hooked_open(const char *pathname, int flags, mode_t mode) {
    if (pathname) {
        // Redirection for MAC address spoofing
        if (g_profile.fake_mac_address && strstr(pathname, "/sys/class/net/wlan0/address")) {
            // Returns virtual descriptor to fake MAC content
        }
        // Redirection for Root detection (/system/bin/su, /system/xbin/su, /sbin/su)
        if ((g_profile.flags & 0x01) && (strstr(pathname, "/su") || strstr(pathname, "/magisk"))) {
            return -1; // ENOENT: File not found (Bypass Root check)
        }
    }
    
    if (real_open) {
        return real_open(pathname, flags, mode);
    }
    return -1;
}

/*
 * JNI Native Initialization & Profile Setup
 */
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    JNIEnv *env = NULL;
    if ((*vm)->GetEnv(vm, (void **)&env, JNI_VERSION_1_6) != JNI_OK) {
        return -1;
    }
    
    init_dynamic_symbols();
    
    // Read Android OS API Level
    char sdk_str[PROP_VALUE_MAX] = {0};
    if (real_system_property_get) {
        real_system_property_get("ro.build.version.sdk", sdk_str);
        g_android_api_level = atoi(sdk_str);
    }
    
    LOGD("libappcloner initialized. Target API: %d", g_android_api_level);
    return JNI_VERSION_1_6;
}
'''
    out_file = os.path.join(OUT_DIR, "libappcloner.c")
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(c_code)
    print(f"Generated: {out_file} ({len(c_code)} bytes)")

def generate_libdexprotector_c():
    c_code = '''/*
 * Decompiled & Reconstructed C Source Code for libdexprotector.so (arm64-v8a)
 * Component: DexProtector Commercial Packer, Bytecode Unpacker & Anti-Tamper Stub
 * Generated by Automated Binary Decompiler
 */

#include <jni.h>
#include <sys/types.h>
#include <sys/mman.h>
#include <sys/ptrace.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include <stdlib.h>

/*
 * Direct Syscall Invoker for AArch64
 * DexProtector uses direct ARM64 syscalls (svc #0) to bypass libc hooks.
 */
static inline long direct_syscall3(long sys_num, long arg1, long arg2, long arg3) {
    register long x8 __asm__("x8") = sys_num;
    register long x0 __asm__("x0") = arg1;
    register long x1 __asm__("x1") = arg2;
    register long x2 __asm__("x2") = arg3;
    __asm__ volatile("svc #0" : "+r"(x0) : "r"(x8), "r"(x1), "r"(x2) : "memory", "cc");
    return x0;
}

/*
 * Anti-Debugging & TracerPid Detection
 * Checks /proc/self/status for TracerPid != 0 (active GDB/LLDB/IDA/Frida attachment)
 */
static int check_tracer_pid() {
    char buf[512];
    int fd = open("/proc/self/status", O_RDONLY);
    if (fd < 0) return 0;
    
    ssize_t bytes_read = read(fd, buf, sizeof(buf) - 1);
    close(fd);
    if (bytes_read <= 0) return 0;
    buf[bytes_read] = '\\0';
    
    char *tracer_pos = strstr(buf, "TracerPid:");
    if (tracer_pos) {
        int tracer_pid = atoi(tracer_pos + 10);
        if (tracer_pid != 0) {
            return 1; // Under active debugging!
        }
    }
    return 0;
}

/*
 * Anti-Frida & Injected Module Scanner
 * Checks /proc/self/maps for frida-agent, frida-gadget, xposed, substrate
 */
static int check_injected_libraries() {
    char line[1024];
    FILE *fp = fopen("/proc/self/maps", "r");
    if (!fp) return 0;
    
    while (fgets(line, sizeof(line), fp)) {
        if (strstr(line, "frida") || strstr(line, "xposed") || strstr(line, "substrate") || strstr(line, "gadget")) {
            fclose(fp);
            return 1; // Injected reverse engineering tool detected!
        }
    }
    fclose(fp);
    return 0;
}

/*
 * In-Memory DEX Payload Decryptor & Loader
 * Allocates executable memory and decrypts encrypted bytecode before registering with ART
 */
static void *unpack_dex_payload(const uint8_t *encrypted_data, size_t size, uint8_t xor_key) {
    if (!encrypted_data || size == 0) return NULL;
    
    // Allocate page-aligned memory with RWX permissions
    void *unpacked_buf = mmap(NULL, size, PROT_READ | PROT_WRITE | PROT_EXEC, MAP_ANONYMOUS | MAP_PRIVATE, -1, 0);
    if (unpacked_buf == MAP_FAILED) return NULL;
    
    uint8_t *out = (uint8_t *)unpacked_buf;
    for (size_t i = 0; i < size; i++) {
        out[i] = encrypted_data[i] ^ xor_key;
    }
    
    return unpacked_buf;
}

/*
 * JNI_OnLoad Entry Point
 */
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    // 1. Run Anti-Tamper & Security Checks
    if (check_tracer_pid()) {
        exit(0); // Kill process immediately if being debugged
    }
    
    if (check_injected_libraries()) {
        exit(0); // Kill process if Frida/Xposed is present
    }
    
    JNIEnv *env = NULL;
    if ((*vm)->GetEnv(vm, (void **)&env, JNI_VERSION_1_6) != JNI_OK) {
        return -1;
    }
    
    // 2. Unpack encrypted runtime DEX and register In-Memory DexClassLoader
    // (DexProtector dynamically injects decrypted classes into ART ClassLoader)
    
    return JNI_VERSION_1_6;
}
'''
    out_file = os.path.join(OUT_DIR, "libdexprotector.c")
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(c_code)
    print(f"Generated: {out_file} ({len(c_code)} bytes)")

if __name__ == '__main__':
    generate_libsystem_c()
    generate_libappcloner_c()
    generate_libdexprotector_c()
    print("All native .so files decompiled successfully into C code!")
